-- Execute no SQL Editor do Supabase

INSERT INTO users (username, email, name, role, is_active, is_online, allowed_tabs, created_at, updated_at)
VALUES
  ('gafolgosi', 'gafolgosi@gruporoveri.com', 'GABRIELLA TONON FOLGOSI', 'operator', true, false, '{}', NOW(), NOW()),
  ('dandsilva', 'dandsilva@gruporoveri.com', 'DANIELE DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('janascimento', 'janascimento@gruporoveri.com', 'JULIA ALEXANDRA SOUZA NASCIMENTO', 'operator', true, false, '{}', NOW(), NOW()),
  ('jovdias', 'jovdias@gruporoveri.com', 'JOAO VICTOR OLIVEIRA DIAS', 'operator', true, false, '{}', NOW(), NOW()),
  ('visousa', 'visousa@gruporoveri.com', 'VITORIA EMANUELE GOMES DE SOUSA', 'operator', true, false, '{}', NOW(), NOW()),
  ('recordeiro', 'recordeiro@gruporoveri.com', 'RENATA CORDEIRO', 'operator', true, false, '{}', NOW(), NOW()),
  ('cananda', 'cananda@gruporoveri.com', 'CAROLINA FERNANDA PEDRA DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('nassis', 'nassis@gruporoveri.com', 'NATASHA ASSIS DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('alemelo', 'alemelo@gruporoveri.com', 'ALESSANDRA SANTOS DE MELO', 'operator', true, false, '{}', NOW(), NOW()),
  ('pcbezerra', 'pcbezerra@gruporoveri.com', 'PAOLA CANDIDA BEZERRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('jeleite', 'jeleite@gruporoveri.com', 'JEFFERSON DE SOUSA LEITE', 'operator', true, false, '{}', NOW(), NOW()),
  ('bnardiva', 'bnardiva@gruporoveri.com', 'BERNARDO SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('majustino', 'majustino@gruporoveri.com', 'MAYARA THAYNA DE JESUS JUSTINO', 'operator', true, false, '{}', NOW(), NOW()),
  ('viaguiar', 'viaguiar@gruporoveri.com', 'VITORIA CAMPOS AGUIAR', 'operator', true, false, '{}', NOW(), NOW()),
  ('mocorreia', 'mocorreia@gruporoveri.com', 'MONIQUE CORREIA', 'operator', true, false, '{}', NOW(), NOW()),
  ('ismingos', 'ismingos@gruporoveri.com', 'ISABELLE DOMINGOS DE LIMA', 'operator', true, false, '{}', NOW(), NOW()),
  ('otvitor', 'otvitor@gruporoveri.com', 'OTAVIO VAILANT VITOR', 'operator', true, false, '{}', NOW(), NOW()),
  ('agmolina', 'agmolina@gruporoveri.com', 'AGATHA MOURA MOLINA', 'operator', true, false, '{}', NOW(), NOW()),
  ('nialbuquerque', 'nialbuquerque@gruporoveri.com', 'NICOLE CAVALCANTE DE ALBUQUERQUE GILI', 'operator', true, false, '{}', NOW(), NOW()),
  ('assilva', 'assilva@gruporoveri.com', 'ASHLEY LANA DE SOUZA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('cimasantos', 'cimasantos@gruporoveri.com', 'CINTIA MARIA GONCALVES DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('besalve', 'besalve@gruporoveri.com', 'BEATRIZ SOARES SALVE', 'operator', true, false, '{}', NOW(), NOW()),
  ('gibueno', 'gibueno@gruporoveri.com', 'GIOVANA GONCALVES DE OLIVEIRA MOURA BUENO', 'operator', true, false, '{}', NOW(), NOW()),
  ('amoliveira', 'amoliveira@gruporoveri.com', 'AMANDA RICCI OLIVEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('lapentos', 'lapentos@gruporoveri.com', 'LARA PEREIRA DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('hedisil', 'hedisil@gruporoveri.com', 'HENRIQUE DIAS DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('rioliveira', 'rioliveira@gruporoveri.com', 'RICHARD ELCIO DE OLIVEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('isabriva', 'isabriva@gruporoveri.com', 'ISAAC BRITO SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('iztesouza', 'iztesouza@gruporoveri.com', 'IZABELLY TEIXEIRA DE SOUZA', 'operator', true, false, '{}', NOW(), NOW()),
  ('brdrecal', 'brdrecal@gruporoveri.com', 'BRUNO ANDRE MARCAL DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('capereira', 'capereira@gruporoveri.com', 'CARLA JANAINA PEREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('chmelo', 'chmelo@gruporoveri.com', 'CHRISTOPHER SILVA MELO', 'operator', true, false, '{}', NOW(), NOW()),
  ('kaalmeida', 'kaalmeida@gruporoveri.com', 'KAIO GABRIEL ALMEIDA', 'operator', true, false, '{}', NOW(), NOW()),
  ('nyrasantos', 'nyrasantos@gruporoveri.com', 'NYCOLLAS ARAUJO DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('anfersilva', 'anfersilva@gruporoveri.com', 'ANDRESSA FERNANDES DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('kabella', 'kabella@gruporoveri.com', 'KARINA GONCIARENCO BELLA', 'operator', true, false, '{}', NOW(), NOW()),
  ('kawpereira', 'kawpereira@gruporoveri.com', 'KAWAN VENTURA PEREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('alvieira', 'alvieira@gruporoveri.com', 'ALICE SANTOS DE ALMEIDA VIEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('gigcabral', 'gigcabral@gruporoveri.com', 'GIOVANNA GONCALVES CABRAL', 'operator', true, false, '{}', NOW(), NOW()),
  ('lubraz', 'lubraz@gruporoveri.com', 'LUANA DIAS BRAZ', 'operator', true, false, '{}', NOW(), NOW()),
  ('stexavier', 'stexavier@gruporoveri.com', 'STEPHANIE XAVIER DE OLIVEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('evmartinez', 'evmartinez@gruporoveri.com', 'EVELLYN SOARES MARTINEZ', 'operator', true, false, '{}', NOW(), NOW()),
  ('lirezende', 'lirezende@gruporoveri.com', 'LILIAN CRISTINA REZENDE', 'operator', true, false, '{}', NOW(), NOW()),
  ('juyetika', 'juyetika@gruporoveri.com', 'JULIA SILVESTRE YETIKA', 'operator', true, false, '{}', NOW(), NOW()),
  ('brpereira', 'brpereira@gruporoveri.com', 'BRENDA ROSARIO DA SILVA PEREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('fedasilva', 'fedasilva@gruporoveri.com', 'FERNANDA DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('fihosantos', 'fihosantos@gruporoveri.com', 'FILIPE HORTA SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('lupinto', 'lupinto@gruporoveri.com', 'LUDMYLA PERESSIN GONCALVES PINTO', 'operator', true, false, '{}', NOW(), NOW()),
  ('musousa', 'musousa@gruporoveri.com', 'MURILO COSTA SOUSA', 'operator', true, false, '{}', NOW(), NOW()),
  ('vijusilva', 'vijusilva@gruporoveri.com', 'VITORIA JULIA ALMEIDA DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('caedsilva', 'caedsilva@gruporoveri.com', 'CARLOS EDUARDO SOUZA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('isvalentim', 'isvalentim@gruporoveri.com', 'ISADORA MARIA DUARTE VALENTIM', 'operator', true, false, '{}', NOW(), NOW()),
  ('pearaujo', 'pearaujo@gruporoveri.com', 'PEDRO HENRIQUE SOARES DE ARAUJO', 'operator', true, false, '{}', NOW(), NOW()),
  ('machado', 'machado@gruporoveri.com', 'MARIA EDUARDA LEITE MACHADO', 'operator', true, false, '{}', NOW(), NOW()),
  ('nidelva', 'nidelva@gruporoveri.com', 'NICOLAS DE OLIVEIRA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('vemendes', 'vemendes@gruporoveri.com', 'VERONICA LEONILIA MENDES', 'operator', true, false, '{}', NOW(), NOW()),
  ('isnascimento', 'isnascimento@gruporoveri.com', 'ISIS TOZZI DO NASCIMENTO', 'operator', true, false, '{}', NOW(), NOW()),
  ('ansantana', 'ansantana@gruporoveri.com', 'ANNA BEATRIZ NOBRE SANTANA', 'operator', true, false, '{}', NOW(), NOW()),
  ('cabueno', 'cabueno@gruporoveri.com', 'CAMILA BUENO DE LIMA', 'operator', true, false, '{}', NOW(), NOW()),
  ('gabacheschi', 'gabacheschi@gruporoveri.com', 'GABRIELLY DE SOUZA BACHESCHI', 'operator', true, false, '{}', NOW(), NOW()),
  ('isacoveira', 'isacoveira@gruporoveri.com', 'ISADORA CORREA DE OLIVEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('gaescaleira', 'gaescaleira@gruporoveri.com', 'GABRIELA CARDOSO ESCALEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('nbgraciano', 'nbgraciano@gruporoveri.com', 'NICHOLAS BERNARDO GRACIANO', 'operator', true, false, '{}', NOW(), NOW()),
  ('rolsantos', 'rolsantos@gruporoveri.com', 'ROBERT LEITE SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('chalencar', 'chalencar@gruporoveri.com', 'CAIO HENRIQUE ARAUJO DE ALENCAR', 'operator', true, false, '{}', NOW(), NOW()),
  ('gaspereira', 'gaspereira@gruporoveri.com', 'GABRIEL SOARES DA SILVA PEREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('gabvsantos', 'gabvsantos@gruporoveri.com', 'GABRIEL VINICIUS DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('jlsobrinho', 'jlsobrinho@gruporoveri.com', 'JOAO DE LIMA MELO SOBRINHO', 'operator', true, false, '{}', NOW(), NOW()),
  ('edunascimento', 'edunascimento@gruporoveri.com', 'EDUARDO SANTOS DO NASCIMENTO', 'operator', true, false, '{}', NOW(), NOW()),
  ('ragoncalves', 'ragoncalves@gruporoveri.com', 'RAFAELA PEREIRA GONCALVES', 'operator', true, false, '{}', NOW(), NOW()),
  ('igpereira', 'igpereira@gruporoveri.com', 'IGOR CHINELATO PEREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('kalves', 'kalves@gruporoveri.com', 'KATIA SANTOS ALVES', 'operator', true, false, '{}', NOW(), NOW()),
  ('miramos', 'miramos@gruporoveri.com', 'MICHELE KAYTHLYN FERREIRA RAMOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('anjamile', 'anjamile@gruporoveri.com', 'ANE JAMILE CARDOSO PEREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('frcosta', 'frcosta@gruporoveri.com', 'FRANCISCA NAZARIO DA COSTA', 'operator', true, false, '{}', NOW(), NOW()),
  ('macristo', 'macristo@gruporoveri.com', 'MARIA PAMELA SILVA DE CRISTO', 'operator', true, false, '{}', NOW(), NOW()),
  ('prissantos', 'prissantos@gruporoveri.com', 'PRISCILA CANDIDA DE OLIVEIRA SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('emteixeira', 'emteixeira@gruporoveri.com', 'EMILLY MUNIZ TEIXEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('yaribeiro', 'yaribeiro@gruporoveri.com', 'YARA RIBEIRO DE OLIVEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('lulelis', 'lulelis@gruporoveri.com', 'LUANA SILVA LELIS', 'operator', true, false, '{}', NOW(), NOW()),
  ('elflima', 'elflima@gruporoveri.com', 'ELIANA FERNANDES DE LIMA', 'operator', true, false, '{}', NOW(), NOW()),
  ('bruborges', 'bruborges@gruporoveri.com', 'BRUNO DOS SANTOS RIBEIRO BORGES', 'operator', true, false, '{}', NOW(), NOW()),
  ('fabigoncalves', 'fabigoncalves@gruporoveri.com', 'FABIANA MURARI GONCALVES', 'operator', true, false, '{}', NOW(), NOW()),
  ('isbarreto', 'isbarreto@gruporoveri.com', 'ISABELLY LIMA BARRETO', 'operator', true, false, '{}', NOW(), NOW()),
  ('elblima', 'elblima@gruporoveri.com', 'ELAINE BISPO SOARES LIMA', 'operator', true, false, '{}', NOW(), NOW()),
  ('joccosta', 'joccosta@gruporoveri.com', 'JOSE CARLOS COSTA', 'operator', true, false, '{}', NOW(), NOW()),
  ('viromagnolo', 'viromagnolo@gruporoveri.com', 'VINICIUS DE ALMEIDA ROMAGNOLO', 'operator', true, false, '{}', NOW(), NOW()),
  ('marnogueira', 'marnogueira@gruporoveri.com', 'MARISA DEMARCHI NOGUEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('anmasilva', 'anmasilva@gruporoveri.com', 'ANDREY MATOS FERREIRA DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('cavisantos', 'cavisantos@gruporoveri.com', 'CAROLINA VITORIA DE ARAUJO SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('edtoledo', 'edtoledo@gruporoveri.com', 'EDUARDA SILVA DE TOLEDO PINTO', 'operator', true, false, '{}', NOW(), NOW()),
  ('mbrito', 'mbrito@gruporoveri.com', 'MARIA EDUARDA DE BRITO SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('rilucindo', 'rilucindo@gruporoveri.com', 'RICHARD MENDES LUCINDO', 'operator', true, false, '{}', NOW(), NOW()),
  ('casimoes', 'casimoes@gruporoveri.com', 'CARINA SIMOES', 'operator', true, false, '{}', NOW(), NOW()),
  ('pehesilva', 'pehesilva@gruporoveri.com', 'PEDRO HENRYQUE SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('kmgoncalves', 'kmgoncalves@gruporoveri.com', 'KEMELLY GONCALVES DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('gainai', 'gainai@gruporoveri.com', 'GABRIELA TYEMI FERRAZ IMAI', 'operator', true, false, '{}', NOW(), NOW()),
  ('maantoniassi', 'maantoniassi@gruporoveri.com', 'MANUELA LEAL ANTONIASSI', 'operator', true, false, '{}', NOW(), NOW()),
  ('feaffonso', 'feaffonso@gruporoveri.com', 'FELIPE GARCIA LOPES AFFONSO', 'operator', true, false, '{}', NOW(), NOW()),
  ('gude', 'gude@gruporoveri.com', 'GUILHERME HENRIQUE OLIVEIRA DE SOUZA', 'operator', true, false, '{}', NOW(), NOW()),
  ('thaysilva', 'thaysilva@gruporoveri.com', 'THAYNARA DOS SANTOS SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('juevangelista', 'juevangelista@gruporoveri.com', 'JULIANE ALVES EVANGELISTA DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('reregio', 'reregio@gruporoveri.com', 'RENATA DE OLIVEIRA REGIO', 'operator', true, false, '{}', NOW(), NOW()),
  ('romartins', 'romartins@gruporoveri.com', 'ROBERT RODRIGUES MARTINS', 'operator', true, false, '{}', NOW(), NOW()),
  ('luclsantos', 'luclsantos@gruporoveri.com', 'LUCAS PEREIRA CLAUDINO DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('calima', 'calima@gruporoveri.com', 'CAMILA FIRMO DE LIMA', 'operator', true, false, '{}', NOW(), NOW()),
  ('kaflima', 'kaflima@gruporoveri.com', 'KARIN FIRMO DE LIMA', 'operator', true, false, '{}', NOW(), NOW()),
  ('jodantas', 'jodantas@gruporoveri.com', 'JOAO VICTOR SILVA ABREU DANTAS', 'operator', true, false, '{}', NOW(), NOW()),
  ('lebafernandes', 'lebafernandes@gruporoveri.com', 'LETICIA BARBOSA FERNANDES', 'operator', true, false, '{}', NOW(), NOW()),
  ('migomes', 'migomes@gruporoveri.com', 'MILLENE DA SILVA GOMES', 'operator', true, false, '{}', NOW(), NOW()),
  ('mareiraza', 'mareiraza@gruporoveri.com', 'MARCELA PEREIRA DE SOUZA', 'operator', true, false, '{}', NOW(), NOW()),
  ('edgracas', 'edgracas@gruporoveri.com', 'EDUARDA BIZARRIA DAS GRACAS', 'operator', true, false, '{}', NOW(), NOW()),
  ('elpimentel', 'elpimentel@gruporoveri.com', 'ELIANE VASCONCELOS PIMENTEL', 'operator', true, false, '{}', NOW(), NOW()),
  ('gasoureis', 'gasoureis@gruporoveri.com', 'GABRIELA SOUZA REIS', 'operator', true, false, '{}', NOW(), NOW()),
  ('jadantas', 'jadantas@gruporoveri.com', 'JAMILE DANTAS DO NASCIMENTO', 'operator', true, false, '{}', NOW(), NOW()),
  ('kecristina', 'kecristina@gruporoveri.com', 'KELEN CRISTINA DE SOUZA DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('begomes', 'begomes@gruporoveri.com', 'BEATRIZ NOVOCHATSKI GOMES', 'operator', true, false, '{}', NOW(), NOW()),
  ('lerrosva', 'lerrosva@gruporoveri.com', 'LEONARDO BARROS SILVA JESUS', 'operator', true, false, '{}', NOW(), NOW()),
  ('emisantos', 'emisantos@gruporoveri.com', 'EMILLY SANTOS DE SOUZA', 'operator', true, false, '{}', NOW(), NOW()),
  ('gadesouza', 'gadesouza@gruporoveri.com', 'GABRIELLY DE SOUSA ALVES', 'operator', true, false, '{}', NOW(), NOW()),
  ('jovictormelo', 'jovictormelo@gruporoveri.com', 'JOAO VICTOR DE MELO MORENO DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('lamorais', 'lamorais@gruporoveri.com', 'LARISSA MORAIS DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('miestefany', 'miestefany@gruporoveri.com', 'MILENA ESTEFANY BORGES DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('thandrade', 'thandrade@gruporoveri.com', 'THAIS ANDRADE SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('afgavezedo', 'afgavezedo@gruporoveri.com', 'ANA FLAVIA GONCALVES DE AZEVEDO', 'operator', true, false, '{}', NOW(), NOW()),
  ('binunes', 'binunes@gruporoveri.com', 'BIANCA SOUSA NUNES', 'operator', true, false, '{}', NOW(), NOW()),
  ('luasousa', 'luasousa@gruporoveri.com', 'LUANA DIAS DE SOUSA', 'operator', true, false, '{}', NOW(), NOW()),
  ('gamergulhao', 'gamergulhao@gruporoveri.com', 'GABRIEL MASCIARELLI FERREIRA MERGULHAO', 'operator', true, false, '{}', NOW(), NOW()),
  ('maaleixo', 'maaleixo@gruporoveri.com', 'MAYSA CARLA ALEIXO', 'operator', true, false, '{}', NOW(), NOW()),
  ('frsousa', 'frsousa@gruporoveri.com', 'FRANCILENE MACIEL SOUSA', 'operator', true, false, '{}', NOW(), NOW()),
  ('juleite', 'juleite@gruporoveri.com', 'JULIA MARINHO LEITE', 'operator', true, false, '{}', NOW(), NOW()),
  ('criferreira', 'criferreira@gruporoveri.com', 'CRISLANE FERREIRA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('giferraz', 'giferraz@gruporoveri.com', 'GIOVANNA DA SILVA FERRAZ', 'operator', true, false, '{}', NOW(), NOW()),
  ('michessantos', 'michessantos@gruporoveri.com', 'MICHELLY DA SILVA SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('nateoliveira', 'nateoliveira@gruporoveri.com', 'NATELLY SALGADO DE OLIVEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('yamarques', 'yamarques@gruporoveri.com', 'YASMIM LAIS SANTOS REIS MARQUES', 'operator', true, false, '{}', NOW(), NOW()),
  ('jucerqueira', 'jucerqueira@gruporoveri.com', 'JULIANA CERQUEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('rodisgoncalves', 'rodisgoncalves@gruporoveri.com', 'ROSIANE DE SOUSA GONCALVES', 'operator', true, false, '{}', NOW(), NOW()),
  ('hereis', 'hereis@gruporoveri.com', 'HENRY KAIQUE FERREIRA REIS', 'operator', true, false, '{}', NOW(), NOW()),
  ('diferraz', 'diferraz@gruporoveri.com', 'DIOGO ALMEIDA FERRAZ', 'operator', true, false, '{}', NOW(), NOW()),
  ('nicabros', 'nicabros@gruporoveri.com', 'NICOLE CABRELON DOS PASSOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('yastheiro', 'yastheiro@gruporoveri.com', 'YARA STHEFFANY DA SILVA RIBEIRO', 'operator', true, false, '{}', NOW(), NOW()),
  ('asleal', 'asleal@gruporoveri.com', 'ARTHUR DE SOUSA LEAL', 'operator', true, false, '{}', NOW(), NOW()),
  ('adantas', 'adantas@gruporoveri.com', 'ALAN DANTAS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('kosantos', 'kosantos@gruporoveri.com', 'KAROLAINE OLIVEIRA SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('maarodrogues', 'maarodrogues@gruporoveri.com', 'MARIA APARECIDA RODRIGUES FARIAS', 'operator', true, false, '{}', NOW(), NOW()),
  ('elvieira', 'elvieira@gruporoveri.com', 'ELDA REGIANE BALERO VIEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('mcferreirta', 'mcferreirta@gruporoveri.com', 'MARIA CLAUDIA FERREIRA DO NASCIMENTO', 'operator', true, false, '{}', NOW(), NOW()),
  ('cnunes', 'cnunes@gruporoveri.com', 'CRISTIANE NUNES DE OLIVEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('naypereira', 'naypereira@gruporoveri.com', 'NAYARA PEREIRA DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('jodiniz', 'jodiniz@gruporoveri.com', 'JOYCE DINIZ SOUZA', 'operator', true, false, '{}', NOW(), NOW()),
  ('stgaloro', 'stgaloro@gruporoveri.com', 'STHEU SCANCANI GALORO', 'operator', true, false, '{}', NOW(), NOW()),
  ('inpsantos', 'inpsantos@gruporoveri.com', 'INES PEREIRA DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('vixalega', 'vixalega@gruporoveri.com', 'VICTOR FREITAS XALEGA', 'operator', true, false, '{}', NOW(), NOW()),
  ('mafeitosa', 'mafeitosa@gruporoveri.com', 'MARIA STEFANE MENDS FEITOSA', 'operator', true, false, '{}', NOW(), NOW()),
  ('jenisilva', 'jenisilva@gruporoveri.com', 'JENIFER MARTINS DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('sicarvalho', 'sicarvalho@gruporoveri.com', 'SIMONE DE CARVALHO SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('evspereira', 'evspereira@gruporoveri.com', 'EVELLYN SILVA PEREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('sineves', 'sineves@gruporoveri.com', 'SILMEIA SANTANA NEVES', 'operator', true, false, '{}', NOW(), NOW()),
  ('luneves', 'luneves@gruporoveri.com', 'LUCIANA RAPOZO NEVES', 'operator', true, false, '{}', NOW(), NOW()),
  ('istoledo', 'istoledo@gruporoveri.com', 'ISABELLY BUENO DE PAULA TOLEDO', 'operator', true, false, '{}', NOW(), NOW()),
  ('jaferreira', 'jaferreira@gruporoveri.com', 'JANIA APARECIDA DOS SANTOS FERREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('maclareira', 'maclareira@gruporoveri.com', 'MARIA CLARA DA SILVA PEREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('npelegrini', 'npelegrini@gruporoveri.com', 'NATHALY DA SILVA PELEGRINI', 'operator', true, false, '{}', NOW(), NOW()),
  ('isdosilva', 'isdosilva@gruporoveri.com', 'ISABELLA DOS SANTOS SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('luviana', 'luviana@gruporoveri.com', 'LUAN SOUSA VIANA', 'operator', true, false, '{}', NOW(), NOW()),
  ('viapevedo', 'viapevedo@gruporoveri.com', 'VIVIANE APARECIDA DE AZEVEDO', 'operator', true, false, '{}', NOW(), NOW()),
  ('roradaju', 'roradaju@gruporoveri.com', 'ROBSON RAMOS DA FONSECA JUNIOR', 'operator', true, false, '{}', NOW(), NOW()),
  ('brnsilva', 'brnsilva@gruporoveri.com', 'BRUNO NOVAIS DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('sesantos', 'sesantos@gruporoveri.com', 'SEVERINA RIBEIRO DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('lamysouza', 'lamysouza@gruporoveri.com', 'LARISSA MYUKI OLIVEIRA SOUZA', 'operator', true, false, '{}', NOW(), NOW()),
  ('pacyele', 'pacyele@gruporoveri.com', 'PAULA GRACYELE OLIVEIRA DE ALMEIDA', 'operator', true, false, '{}', NOW(), NOW()),
  ('jubarros', 'jubarros@gruporoveri.com', 'JULIA SOARES BARROS', 'operator', true, false, '{}', NOW(), NOW()),
  ('iasousa', 'iasousa@gruporoveri.com', 'IARA PEREIRA SOUSA', 'operator', true, false, '{}', NOW(), NOW()),
  ('maduardo', 'maduardo@gruporoveri.com', 'MARCOS EDUARDO DE NOVAES SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('yapierri', 'yapierri@gruporoveri.com', 'YASMIN PIERRI', 'operator', true, false, '{}', NOW(), NOW()),
  ('najsouza', 'najsouza@gruporoveri.com', 'NAARA DE JESUS SOUZA', 'operator', true, false, '{}', NOW(), NOW()),
  ('befreitas', 'befreitas@gruporoveri.com', 'BERNARDO DE PAIVA FREITAS', 'operator', true, false, '{}', NOW(), NOW()),
  ('cisotocorno', 'cisotocorno@gruporoveri.com', 'CINTHIA DE OLIVEIRA SOTOCORNO', 'operator', true, false, '{}', NOW(), NOW()),
  ('thxalmeida', 'thxalmeida@gruporoveri.com', 'THALIA XAVIER DE ALMEIDA', 'operator', true, false, '{}', NOW(), NOW()),
  ('rulopes', 'rulopes@gruporoveri.com', 'RUI SOBREIRA LOPES', 'operator', true, false, '{}', NOW(), NOW()),
  ('cilima', 'cilima@gruporoveri.com', 'CINTIA DANIEL LIMA', 'operator', true, false, '{}', NOW(), NOW()),
  ('yanascimento', 'yanascimento@gruporoveri.com', 'YANNE KARYNE FREITAS DO NASCIMENTO', 'operator', true, false, '{}', NOW(), NOW()),
  ('lagarcia', 'lagarcia@gruporoveri.com', 'LARICE BENTO GARCIA', 'operator', true, false, '{}', NOW(), NOW()),
  ('kaalvieira', 'kaalvieira@gruporoveri.com', 'KALIL DE ALMEIDA VIEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('malisilva', 'malisilva@gruporoveri.com', 'MARIA EDUARDA LIMA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('luujlaki', 'luujlaki@gruporoveri.com', 'LUCAS TAMASHIRO UJLAKI', 'operator', true, false, '{}', NOW(), NOW()),
  ('andrferreira', 'andrferreira@gruporoveri.com', 'ANDREIA ALBERTO FURTADO FERREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('ankatia', 'ankatia@gruporoveri.com', 'ANA KATIA DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('feaguiar', 'feaguiar@gruporoveri.com', 'FELIPE AGUIAR MENDES DO NASCIMENTO', 'operator', true, false, '{}', NOW(), NOW()),
  ('carsnunes', 'carsnunes@gruporoveri.com', 'CAROLINA NUNES DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('anparodrigues', 'anparodrigues@gruporoveri.com', 'ANA PAULA RODRIGUES', 'operator', true, false, '{}', NOW(), NOW()),
  ('inanisilva', 'inanisilva@gruporoveri.com', 'INGRID ANISIO DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('kasantana', 'kasantana@gruporoveri.com', 'KATHELLYN IASMIM ROSA SANTANA', 'operator', true, false, '{}', NOW(), NOW()),
  ('clunguinho', 'clunguinho@gruporoveri.com', 'CARLOS EDUARDO LUNGUINHO DE OLIVEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('rupablo', 'rupablo@gruporoveri.com', 'RUAN PABLO DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('thferreira', 'thferreira@gruporoveri.com', 'THAINA GUIMARAES FERREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('lueilima', 'lueilima@gruporoveri.com', 'LUCAS EIRISDAN OLIVEIRA LIMA', 'operator', true, false, '{}', NOW(), NOW()),
  ('yaosman', 'yaosman@gruporoveri.com', 'YASMIN YOUSSEF ABOU OSMAN', 'operator', true, false, '{}', NOW(), NOW()),
  ('iscavalcante', 'iscavalcante@gruporoveri.com', 'ISAIANY FERNANDA RAMALHO CAVALCANTE', 'operator', true, false, '{}', NOW(), NOW()),
  ('rubrady', 'rubrady@gruporoveri.com', 'RUBIA BRADY', 'operator', true, false, '{}', NOW(), NOW()),
  ('helisilva', 'helisilva@gruporoveri.com', 'HENRIQUE LINO DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('dacastro', 'dacastro@gruporoveri.com', 'DANIELE NUNES DE CASTRO', 'operator', true, false, '{}', NOW(), NOW()),
  ('anjimenez', 'anjimenez@gruporoveri.com', 'ANNE CAROLINE SILVA JIMENEZ', 'operator', true, false, '{}', NOW(), NOW()),
  ('enquiles', 'enquiles@gruporoveri.com', 'ENZO FERREIRA QUILES', 'operator', true, false, '{}', NOW(), NOW()),
  ('adgenerali', 'adgenerali@gruporoveri.com', 'ADRIANA GENERALI', 'operator', true, false, '{}', NOW(), NOW()),
  ('alram', 'alram@gruporoveri.com', 'ALECSANDRO GABRIEL MACHADO RAMOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('deesequiel', 'deesequiel@gruporoveri.com', 'DENNER OLIVEIRA ESEQUIEL', 'operator', true, false, '{}', NOW(), NOW()),
  ('amvidoy', 'amvidoy@gruporoveri.com', 'AMANDA VIANA GODOY SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('pavaz', 'pavaz@gruporoveri.com', 'PALOMA MARQUES APOLIANO VAZ', 'operator', true, false, '{}', NOW(), NOW()),
  ('givrodrigues', 'givrodrigues@gruporoveri.com', 'GIOVANNA VALERIA RODRIGUES', 'operator', true, false, '{}', NOW(), NOW()),
  ('nifreitas', 'nifreitas@gruporoveri.com', 'NICOLY AMARAL DE FREITAS', 'operator', true, false, '{}', NOW(), NOW()),
  ('alaquina', 'alaquina@gruporoveri.com', 'ALEXANDRINA FIGUEIREDO DE AQUINO', 'operator', true, false, '{}', NOW(), NOW()),
  ('encozzolino', 'encozzolino@gruporoveri.com', 'ENZO GONCALVES COZZOLINO', 'operator', true, false, '{}', NOW(), NOW()),
  ('adlopes', 'adlopes@gruporoveri.com', 'ADRIANO PALMEIRA LOPES', 'operator', true, false, '{}', NOW(), NOW()),
  ('larialves', 'larialves@gruporoveri.com', 'LARISSA ARIADNE COUTINHO CARVALHO ALVES', 'operator', true, false, '{}', NOW(), NOW()),
  ('magelima', 'magelima@gruporoveri.com', 'MARIA GENILDA DE ARAUJO LIMA', 'operator', true, false, '{}', NOW(), NOW()),
  ('jemsilva', 'jemsilva@gruporoveri.com', 'JENIFER MAIRA LIMA DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('feviana', 'feviana@gruporoveri.com', 'FERNANDA DE OLIVEIRA VIANA', 'operator', true, false, '{}', NOW(), NOW()),
  ('jocaetano', 'jocaetano@gruporoveri.com', 'JOICE VITAL CAETANO', 'operator', true, false, '{}', NOW(), NOW()),
  ('lafraga', 'lafraga@gruporoveri.com', 'LARISSA DA SILVA FRAGA', 'operator', true, false, '{}', NOW(), NOW()),
  ('vtrbatista', 'vtrbatista@gruporoveri.com', 'VITORIA SILVA BATISTA', 'operator', true, false, '{}', NOW(), NOW()),
  ('cismailva', 'cismailva@gruporoveri.com', 'CICERA MARIA DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('vibrito', 'vibrito@gruporoveri.com', 'VINICIUS DE LIMA BRITO', 'operator', true, false, '{}', NOW(), NOW()),
  ('jolubeiro', 'jolubeiro@gruporoveri.com', 'JOAO LUCAS LOPES RIBEIRO', 'operator', true, false, '{}', NOW(), NOW()),
  ('jelima', 'jelima@gruporoveri.com', 'JESSICA CAROLINE SANTOS LIMA', 'operator', true, false, '{}', NOW(), NOW()),
  ('ismodesto', 'ismodesto@gruporoveri.com', 'ISABELLE DE ARAUJO MODESTO', 'operator', true, false, '{}', NOW(), NOW()),
  ('ligomes', 'ligomes@gruporoveri.com', 'LISLIE MENDES GOMES', 'operator', true, false, '{}', NOW(), NOW()),
  ('fevido', 'fevido@gruporoveri.com', 'FERNANDA VICTORIA ISIDORO LINHARES DE FREITAS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('getargino', 'getargino@gruporoveri.com', 'GEOVANA PALMA ALBUQUERQUE TARGINO', 'operator', true, false, '{}', NOW(), NOW()),
  ('joviervalho', 'joviervalho@gruporoveri.com', 'JOAO VITOR XAVIER DE CARVALHO', 'operator', true, false, '{}', NOW(), NOW()),
  ('maclaro', 'maclaro@gruporoveri.com', 'MARIA APARECIDA CLARO', 'operator', true, false, '{}', NOW(), NOW()),
  ('vitosva', 'vitosva@gruporoveri.com', 'VITORIA SANTOS SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('gusimiao', 'gusimiao@gruporoveri.com', 'GUILHERME FERRARIA DE OLIVEIRA SIMIAO', 'operator', true, false, '{}', NOW(), NOW()),
  ('rocoelho', 'rocoelho@gruporoveri.com', 'ROBERTA DOS SANTOS COELHO', 'operator', true, false, '{}', NOW(), NOW()),
  ('becosta', 'becosta@gruporoveri.com', 'BEATRIZ IZABEL DA COSTA', 'operator', true, false, '{}', NOW(), NOW()),
  ('isavenancio', 'isavenancio@gruporoveri.com', 'ISABELA DA SILVA VENANCIO DE SOUSA', 'operator', true, false, '{}', NOW(), NOW()),
  ('ribarbosa', 'ribarbosa@gruporoveri.com', 'RICHELME LEVI EMIDIO BARBOSA', 'operator', true, false, '{}', NOW(), NOW()),
  ('rapaz', 'rapaz@gruporoveri.com', 'RAFAELLA GARCIA DA PAZ', 'operator', true, false, '{}', NOW(), NOW()),
  ('gigcarmargo', 'gigcarmargo@gruporoveri.com', 'GIULIA DE CAMARGO GONCALVES', 'operator', true, false, '{}', NOW(), NOW()),
  ('ialisboa', 'ialisboa@gruporoveri.com', 'IAN DO CARMO LISBOA', 'operator', true, false, '{}', NOW(), NOW()),
  ('macunha', 'macunha@gruporoveri.com', 'MARIA APARECIDA PEREIRA CUNHA', 'operator', true, false, '{}', NOW(), NOW()),
  ('pamiranda', 'pamiranda@gruporoveri.com', 'PATRICK CARMO DE MIRANDA', 'operator', true, false, '{}', NOW(), NOW()),
  ('sabmedeiros', 'sabmedeiros@gruporoveri.com', 'SABRINA NUNES DE MEDEIROS', 'operator', true, false, '{}', NOW(), NOW()),
  ('dadcosta', 'dadcosta@gruporoveri.com', 'DAVI MEDEIROS DA COSTA', 'operator', true, false, '{}', NOW(), NOW()),
  ('vilopes', 'vilopes@gruporoveri.com', 'VITOR MENDONCA LOPES', 'operator', true, false, '{}', NOW(), NOW()),
  ('bifoliveira', 'bifoliveira@gruporoveri.com', 'BIANCA FARIAS DE OLIVEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('elesilva', 'elesilva@gruporoveri.com', 'ELETICIA SOUZA DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('marilima', 'marilima@gruporoveri.com', 'MARIANI SILVA DE LIMA', 'operator', true, false, '{}', NOW(), NOW()),
  ('velage', 'velage@gruporoveri.com', 'VERONICA CAVALCANTE LAGE', 'operator', true, false, '{}', NOW(), NOW()),
  ('luabreu', 'luabreu@gruporoveri.com', 'LUCAS DELLA BIANCA ABREU', 'operator', true, false, '{}', NOW(), NOW()),
  ('beramires', 'beramires@gruporoveri.com', 'BEATRIZ TAVARES RAMIRES', 'operator', true, false, '{}', NOW(), NOW()),
  ('namatias', 'namatias@gruporoveri.com', 'NALANDA PEREIRA MATIAS', 'operator', true, false, '{}', NOW(), NOW()),
  ('brsantos', 'brsantos@gruporoveri.com', 'BRIAN PIERRY DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('daalves', 'daalves@gruporoveri.com', 'DANILO BARBOSA PAULINO ALVES', 'operator', true, false, '{}', NOW(), NOW()),
  ('prlagorga', 'prlagorga@gruporoveri.com', 'PRISCILA LAGORGA', 'operator', true, false, '{}', NOW(), NOW()),
  ('helira', 'helira@gruporoveri.com', 'HENRY NEGRETTI DE LIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('aufortesa', 'aufortesa@gruporoveri.com', 'AUGUSTO RODRIGUES FORTESA', 'operator', true, false, '{}', NOW(), NOW()),
  ('jocosta', 'jocosta@gruporoveri.com', 'JOAO VICTOR SILVA COSTA', 'operator', true, false, '{}', NOW(), NOW()),
  ('lejustiniano', 'lejustiniano@gruporoveri.com', 'LEONARDO SANTOS JUSTINIANO', 'operator', true, false, '{}', NOW(), NOW()),
  ('fevirches', 'fevirches@gruporoveri.com', 'FELIPE PICULI VIRCHES', 'operator', true, false, '{}', NOW(), NOW()),
  ('nimuniz', 'nimuniz@gruporoveri.com', 'NILIANE DE NAZARE VASCONCELOS MUNIZ', 'operator', true, false, '{}', NOW(), NOW()),
  ('sarsantana', 'sarsantana@gruporoveri.com', 'SAMIR ASSUNCAO SANTANA', 'operator', true, false, '{}', NOW(), NOW()),
  ('sopjesus', 'sopjesus@gruporoveri.com', 'SOPHIA DE JESUS FERREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('luzzuto', 'luzzuto@gruporoveri.com', 'LUANNY RIZZUTO FERREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('thalvestos', 'thalvestos@gruporoveri.com', 'THAYNA ALVES DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('nagomes', 'nagomes@gruporoveri.com', 'NATHALIA DIAS GOMES', 'operator', true, false, '{}', NOW(), NOW()),
  ('pabeneti', 'pabeneti@gruporoveri.com', 'PAULO BENETI DE SOUZA GOMES', 'operator', true, false, '{}', NOW(), NOW()),
  ('raforratini', 'raforratini@gruporoveri.com', 'RAYANE CRISTINA FORRATINI', 'operator', true, false, '{}', NOW(), NOW()),
  ('rivalerio', 'rivalerio@gruporoveri.com', 'RITA CLAYCIA SOARES VALERIO', 'operator', true, false, '{}', NOW(), NOW()),
  ('romanoel', 'romanoel@gruporoveri.com', 'ROBERTA MANOEL', 'operator', true, false, '{}', NOW(), NOW()),
  ('streis', 'streis@gruporoveri.com', 'STEFANIE FERREIRA REIS', 'operator', true, false, '{}', NOW(), NOW()),
  ('guigomess', 'guigomess@gruporoveri.com', 'GUILHERME MOREIRA GOMES FERREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('pansantos', 'pansantos@gruporoveri.com', 'PAULA NATALIA SILVA SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('anluz', 'anluz@gruporoveri.com', 'ANA CAROLINE SILVA LUZ DE OLIVEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('gianzolin', 'gianzolin@gruporoveri.com', 'GIOVANNA PAREJA ANZOLIN', 'operator', true, false, '{}', NOW(), NOW()),
  ('rogesilva', 'rogesilva@gruporoveri.com', 'ROGERIO SILVA RODRIGUES', 'operator', true, false, '{}', NOW(), NOW()),
  ('mucampoli', 'mucampoli@gruporoveri.com', 'MURILO CAMPOLI DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('jhonsilva', 'jhonsilva@gruporoveri.com', 'JHONATAN MONTEIRO DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('yamelo', 'yamelo@gruporoveri.com', 'YASMIM DA SILVA MELO', 'operator', true, false, '{}', NOW(), NOW()),
  ('taasilva', 'taasilva@gruporoveri.com', 'TAINA APARECIDA SALES DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('mafretegotto', 'mafretegotto@gruporoveri.com', 'MARIA TEREZA FRETEGOTTO', 'operator', true, false, '{}', NOW(), NOW()),
  ('kasa', 'kasa@gruporoveri.com', 'KAREN CARVALHO DE SA', 'operator', true, false, '{}', NOW(), NOW()),
  ('brabrao', 'brabrao@gruporoveri.com', 'BRUNO RAFAEL DOS SANTOS ABRAO', 'operator', true, false, '{}', NOW(), NOW()),
  ('majmelo', 'majmelo@gruporoveri.com', 'MARIA JOSE SILVA DE MELO', 'operator', true, false, '{}', NOW(), NOW()),
  ('kabarbosa', 'kabarbosa@gruporoveri.com', 'KAUAI RODRIGUES BARBOSA', 'operator', true, false, '{}', NOW(), NOW()),
  ('mursouza', 'mursouza@gruporoveri.com', 'MURILO ESTEVAM DE SOUZA', 'operator', true, false, '{}', NOW(), NOW()),
  ('rybazan', 'rybazan@gruporoveri.com', 'RYAN CAVINATO BAZAN', 'operator', true, false, '{}', NOW(), NOW()),
  ('edalves', 'edalves@gruporoveri.com', 'EDER NASCIMENTO ALVES', 'operator', true, false, '{}', NOW(), NOW()),
  ('ermpereira', 'ermpereira@gruporoveri.com', 'ERIKA MACIEL PEREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('thlourenco', 'thlourenco@gruporoveri.com', 'THAIS SANTOS LOURENCO', 'operator', true, false, '{}', NOW(), NOW()),
  ('bpenacchio', 'bpenacchio@gruporoveri.com', 'BEATTRIZ PENACCHIO RIBEIRO SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('lelucindo', 'lelucindo@gruporoveri.com', 'LETICIA RANY MENDES LUCINDO', 'operator', true, false, '{}', NOW(), NOW()),
  ('mascucuglia', 'mascucuglia@gruporoveri.com', 'MATHEUS ALVES ELLERN SCUCUGLIA', 'operator', true, false, '{}', NOW(), NOW()),
  ('gealmeida', 'gealmeida@gruporoveri.com', 'GEOVANNA APARECIDA ALMEIDA DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('sioliveira', 'sioliveira@gruporoveri.com', 'SILVIA REGINA DE OLIVEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('hunascimento', 'hunascimento@gruporoveri.com', 'HUGO CAVALCANTE DO NASCIMENTO', 'operator', true, false, '{}', NOW(), NOW()),
  ('locura', 'locura@gruporoveri.com', 'LORENA LANGANKE CURA', 'operator', true, false, '{}', NOW(), NOW()),
  ('nabaleeiro', 'nabaleeiro@gruporoveri.com', 'NATACHA FREITAS BALEEIRO', 'operator', true, false, '{}', NOW(), NOW()),
  ('vatossato', 'vatossato@gruporoveri.com', 'VANESSA TOSSATO', 'operator', true, false, '{}', NOW(), NOW()),
  ('madusouza', 'madusouza@gruporoveri.com', 'MARIA EDUARDA SILVA DE SOUZA', 'operator', true, false, '{}', NOW(), NOW()),
  ('idaniela', 'idaniela@gruporoveri.com', 'INGRID DANIELA BENTO DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('hapereira', 'hapereira@gruporoveri.com', 'HAYALA VITORIA SILVA PEREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('erirocha', 'erirocha@gruporoveri.com', 'ERICK ROCHA DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('anluiza', 'anluiza@gruporoveri.com', 'ANA LUIZA DE OLIVEIRA GONCALVES', 'operator', true, false, '{}', NOW(), NOW()),
  ('lumota', 'lumota@gruporoveri.com', 'LUAN SANTOS MOTA', 'operator', true, false, '{}', NOW(), NOW()),
  ('pesanches', 'pesanches@gruporoveri.com', 'PEDRO LUIGI PALMA SANCHES', 'operator', true, false, '{}', NOW(), NOW()),
  ('rireis', 'rireis@gruporoveri.com', 'RICHARD VITOR SILVA DOS REIS', 'operator', true, false, '{}', NOW(), NOW()),
  ('arcaires', 'arcaires@gruporoveri.com', 'ARTHUR LISBOA CAIRES', 'operator', true, false, '{}', NOW(), NOW()),
  ('dajunior', 'dajunior@gruporoveri.com', 'DANIEL TELES JUNIOR', 'operator', true, false, '{}', NOW(), NOW()),
  ('samoreira', 'samoreira@gruporoveri.com', 'SAMUEL AUGUSTO DE QUEIROZ MOREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('fasus', 'fasus@gruporoveri.com', 'FABIO DE JESUS MARTINS', 'operator', true, false, '{}', NOW(), NOW()),
  ('cagodolfini', 'cagodolfini@gruporoveri.com', 'CAMILLY DE OLIVEIRA GODOLFINI', 'operator', true, false, '{}', NOW(), NOW()),
  ('birodrigues', 'birodrigues@gruporoveri.com', 'BIANCA ESTEFNE RODRIGUES', 'operator', true, false, '{}', NOW(), NOW()),
  ('cllira', 'cllira@gruporoveri.com', 'CLARISSE CAVALCANTE LIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('femessias', 'femessias@gruporoveri.com', 'FELIPE TERRA MESSIAS', 'operator', true, false, '{}', NOW(), NOW()),
  ('jobastos', 'jobastos@gruporoveri.com', 'JOAO VITOR SILVA BASTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('kigonzaga', 'kigonzaga@gruporoveri.com', 'KIMBERLY BUENO GONZAGA', 'operator', true, false, '{}', NOW(), NOW()),
  ('lulucateli', 'lulucateli@gruporoveri.com', 'LUCAS VILELA LUCATELI', 'operator', true, false, '{}', NOW(), NOW()),
  ('namacedo', 'namacedo@gruporoveri.com', 'NATALIA DOS SANTOS MACEDO', 'operator', true, false, '{}', NOW(), NOW()),
  ('satoria', 'satoria@gruporoveri.com', 'SARAH VITORIA DA PAIXAO SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('esribeiro', 'esribeiro@gruporoveri.com', 'ESTER SOUZA RIBEIRO', 'operator', true, false, '{}', NOW(), NOW()),
  ('pasouza', 'pasouza@gruporoveri.com', 'PALOMA PINHEIRO ARAUJO DE SOUZA', 'operator', true, false, '{}', NOW(), NOW()),
  ('anguipoina', 'anguipoina@gruporoveri.com', 'ANTONIO GUILHERME POINA DO NASCIMENTO', 'operator', true, false, '{}', NOW(), NOW()),
  ('breeribeiro', 'breeribeiro@gruporoveri.com', 'BREENDA RIBEIRO SANTOS DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('cacastro', 'cacastro@gruporoveri.com', 'CAROLINE APARECIDA COSTA DE CASTRO', 'operator', true, false, '{}', NOW(), NOW()),
  ('lomelo', 'lomelo@gruporoveri.com', 'LORENA SILVA MELO', 'operator', true, false, '{}', NOW(), NOW()),
  ('nathasilva', 'nathasilva@gruporoveri.com', 'NATHAN DA SILVA SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('rasousa', 'rasousa@gruporoveri.com', 'RAYSSA RODRIGUES SOUSA', 'operator', true, false, '{}', NOW(), NOW()),
  ('savillagra', 'savillagra@gruporoveri.com', 'SABRINA SILVA VILLAGRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('giaraujo', 'giaraujo@gruporoveri.com', 'GIOVANNA DO CARMO ARAUJO', 'operator', true, false, '{}', NOW(), NOW()),
  ('jusouza', 'jusouza@gruporoveri.com', 'JULIA GONCALVES DE SOUZA', 'operator', true, false, '{}', NOW(), NOW()),
  ('otsa', 'otsa@gruporoveri.com', 'OTAVIO SILVA DE SA', 'operator', true, false, '{}', NOW(), NOW()),
  ('brferreira', 'brferreira@gruporoveri.com', 'BRUNO FERREIRA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('ernansilva', 'ernansilva@gruporoveri.com', 'ERICK RENAN DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('jamariasilva', 'jamariasilva@gruporoveri.com', 'JAINE MARIA DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('beferreira', 'beferreira@gruporoveri.com', 'BEATRIZ LEITE FERREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('demariabarros', 'demariabarros@gruporoveri.com', 'DEBORA MARIA BARROS OLIVEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('niduran', 'niduran@gruporoveri.com', 'NINA BARRETO DURAN', 'operator', true, false, '{}', NOW(), NOW()),
  ('vlsousa', 'vlsousa@gruporoveri.com', 'VLAUBERSON DA SILVA VENANCIO DE SOUSA', 'operator', true, false, '{}', NOW(), NOW()),
  ('bemelo', 'bemelo@gruporoveri.com', 'BEATRIZ PEREIRA DE MELO', 'operator', true, false, '{}', NOW(), NOW()),
  ('esthsilva', 'esthsilva@gruporoveri.com', 'ESTHER SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('rebulgarelli', 'rebulgarelli@gruporoveri.com', 'RENAN DA SILVA BULGARELLI', 'operator', true, false, '{}', NOW(), NOW()),
  ('niwitkowaki', 'niwitkowaki@gruporoveri.com', 'NICOLAS WITKOWSKI', 'operator', true, false, '{}', NOW(), NOW()),
  ('brlorodrigues', 'brlorodrigues@gruporoveri.com', 'BRUNO LORENZO RODRIGUES', 'operator', true, false, '{}', NOW(), NOW()),
  ('pehesouza', 'pehesouza@gruporoveri.com', 'PEDRO HENRIQUE ALEXANDRE DIAS DE SOUZA', 'operator', true, false, '{}', NOW(), NOW()),
  ('luschicarelli', 'luschicarelli@gruporoveri.com', 'LUCAS SENA CHICARELLI', 'operator', true, false, '{}', NOW(), NOW()),
  ('alfaria', 'alfaria@gruporoveri.com', 'ALINE DE GOES FARIA', 'operator', true, false, '{}', NOW(), NOW()),
  ('anclveira', 'anclveira@gruporoveri.com', 'ANA CLARA OLIVEIRA LIMA', 'operator', true, false, '{}', NOW(), NOW()),
  ('cacucolicchio', 'cacucolicchio@gruporoveri.com', 'CAIO ZANETTI CUCOLICCHIO', 'operator', true, false, '{}', NOW(), NOW()),
  ('caarcibelli', 'caarcibelli@gruporoveri.com', 'CAUE HENRIQUE ARCIBELLI', 'operator', true, false, '{}', NOW(), NOW()),
  ('jejesus', 'jejesus@gruporoveri.com', 'JERFE FONSECA DE JESUS', 'operator', true, false, '{}', NOW(), NOW()),
  ('maherrera', 'maherrera@gruporoveri.com', 'MARCIO HERRERA', 'operator', true, false, '{}', NOW(), NOW()),
  ('macosousa', 'macosousa@gruporoveri.com', 'MARYANA DA COSTA SOUSA', 'operator', true, false, '{}', NOW(), NOW()),
  ('vizerra', 'vizerra@gruporoveri.com', 'VINICIUS BEZERRA COSTA', 'operator', true, false, '{}', NOW(), NOW()),
  ('hebrito', 'hebrito@gruporoveri.com', 'HENRIQUE MITSUNARI DE BRITO', 'operator', true, false, '{}', NOW(), NOW()),
  ('nicossouza', 'nicossouza@gruporoveri.com', 'NICOLAS COSTA DE SOUZA', 'operator', true, false, '{}', NOW(), NOW()),
  ('anlaveira', 'anlaveira@gruporoveri.com', 'ANA PAULA DE OLIVEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('dhsilva', 'dhsilva@gruporoveri.com', 'DHOLGIANI SHIRLEI DE MIRANDA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('gatosra', 'gatosra@gruporoveri.com', 'GABRIELLY SANTOS DE OLIVEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('lautrizilva', 'lautrizilva@gruporoveri.com', 'LAURA BEATRIZ DE LIMA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('meperin', 'meperin@gruporoveri.com', 'MEL MELO PERIN', 'operator', true, false, '{}', NOW(), NOW()),
  ('thawsilva', 'thawsilva@gruporoveri.com', 'THAWANNY GEOVANA DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('norezende', 'norezende@gruporoveri.com', 'NOEMI REZENDE ESTEVAM', 'operator', true, false, '{}', NOW(), NOW()),
  ('lslana', 'lslana@gruporoveri.com', 'LUANA DOS SANTOS LANA', 'operator', true, false, '{}', NOW(), NOW()),
  ('rdsousa', 'rdsousa@gruporoveri.com', 'REGINE DE SOUSA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('regaugusto', 'regaugusto@gruporoveri.com', 'REBECA GABRIELI SOUZA AUGUSTO', 'operator', true, false, '{}', NOW(), NOW()),
  ('taamartins', 'taamartins@gruporoveri.com', 'TAINARA AMBROZIO MARTINS', 'operator', true, false, '{}', NOW(), NOW()),
  ('navera', 'navera@gruporoveri.com', 'NATASHA SILVA VERA', 'operator', true, false, '{}', NOW(), NOW()),
  ('thiaraujo', 'thiaraujo@gruporoveri.com', 'THIELLY DE ARAUJO LIMA', 'operator', true, false, '{}', NOW(), NOW()),
  ('thadsilva', 'thadsilva@gruporoveri.com', 'THALIA APARECIDA DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('garoliveira', 'garoliveira@gruporoveri.com', 'GABRIELLA RODRIGUES OLIVEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('tiyonemura', 'tiyonemura@gruporoveri.com', 'TIAGO IORI YONEMURA', 'operator', true, false, '{}', NOW(), NOW()),
  ('saleiras', 'saleiras@gruporoveri.com', 'SANDRA LEOPOLDINO LEIRAS', 'operator', true, false, '{}', NOW(), NOW()),
  ('mimacena', 'mimacena@gruporoveri.com', 'MILENA MACENA OLIVEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('geferreira', 'geferreira@gruporoveri.com', 'GEOVANNA LEANDRO FERREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('marcosilva', 'marcosilva@gruporoveri.com', 'MARCO ANTONIO FERRO SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('lubernardes', 'lubernardes@gruporoveri.com', 'LUIZ HENRIQUE DIAS BERNARDES', 'operator', true, false, '{}', NOW(), NOW()),
  ('raycarvalho', 'raycarvalho@gruporoveri.com', 'RAISLENY DE CARVALHO', 'operator', true, false, '{}', NOW(), NOW()),
  ('aradeo', 'aradeo@gruporoveri.com', 'ARTUR ALVES ADEO', 'operator', true, false, '{}', NOW(), NOW()),
  ('sibertolucci', 'sibertolucci@gruporoveri.com', 'SILVANA COSTA BERTOLUCCI', 'operator', true, false, '{}', NOW(), NOW()),
  ('niboaventura', 'niboaventura@gruporoveri.com', 'NIVEA KATIA DA SILVA BOAVENTURA', 'operator', true, false, '{}', NOW(), NOW()),
  ('kamuniz', 'kamuniz@gruporoveri.com', 'KARINA MUNIZ VIEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('faguirra', 'faguirra@gruporoveri.com', 'FABIO EISHIMA DE CASTRO GUIRRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('jaraimundo', 'jaraimundo@gruporoveri.com', 'JACKSON CINTRA RAIMUNDO', 'operator', true, false, '{}', NOW(), NOW()),
  ('errfato', 'errfato@gruporoveri.com', 'ERIC CATINO RUFATO', 'operator', true, false, '{}', NOW(), NOW()),
  ('gmodesto', 'gmodesto@gruporoveri.com', 'GUILHERME MODESTO LOPES DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('matartari', 'matartari@gruporoveri.com', 'MARISA FRANCIS GUILHERME TARTARI', 'operator', true, false, '{}', NOW(), NOW()),
  ('ferabetti', 'ferabetti@gruporoveri.com', 'FELIPE ZULEGER RABETTI', 'operator', true, false, '{}', NOW(), NOW()),
  ('bnsantos', 'bnsantos@gruporoveri.com', 'BRUNA APARECIDA SILVA SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('gafoalmeida', 'gafoalmeida@gruporoveri.com', 'GABRIEL FOGACA DE CAMPOS ALMEIDA', 'operator', true, false, '{}', NOW(), NOW()),
  ('roguimaraes', 'roguimaraes@gruporoveri.com', 'RONALD BUGHI GUIMARAES', 'operator', true, false, '{}', NOW(), NOW()),
  ('sasgoantos', 'sasgoantos@gruporoveri.com', 'SAMUEL GONCALVES DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('ensutto', 'ensutto@gruporoveri.com', 'ENZO SUTTO', 'operator', true, false, '{}', NOW(), NOW()),
  ('thballeiro', 'thballeiro@gruporoveri.com', 'THIAGO ARAUJO SOUTO BALEEIRO', 'operator', true, false, '{}', NOW(), NOW()),
  ('caedousa', 'caedousa@gruporoveri.com', 'CARLOS EDUARDO DE MOURA SOUSA', 'operator', true, false, '{}', NOW(), NOW()),
  ('hecarvalho', 'hecarvalho@gruporoveri.com', 'HENRIQUE THOME DE CARVALHO', 'operator', true, false, '{}', NOW(), NOW()),
  ('artpaz', 'artpaz@gruporoveri.com', 'ARTHUR DA PAZ BARBOSA', 'operator', true, false, '{}', NOW(), NOW()),
  ('brljesus', 'brljesus@gruporoveri.com', 'BRENDA LEAL DE JESUS', 'operator', true, false, '{}', NOW(), NOW()),
  ('gasolopes', 'gasolopes@gruporoveri.com', 'GABRIEL SOARES LOPES', 'operator', true, false, '{}', NOW(), NOW()),
  ('gusil', 'gusil@gruporoveri.com', 'GUILHERME SOUSA DOS SANTOS SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('levietri', 'levietri@gruporoveri.com', 'LEONARDO MUZATIO VIETRI', 'operator', true, false, '{}', NOW(), NOW()),
  ('lucunha', 'lucunha@gruporoveri.com', 'LUCAS SOARES DA CUNHA', 'operator', true, false, '{}', NOW(), NOW()),
  ('gysales', 'gysales@gruporoveri.com', 'GYOVANNA DOS SANTOS SALES', 'operator', true, false, '{}', NOW(), NOW()),
  ('lelincevicius', 'lelincevicius@gruporoveri.com', 'LEONARDO GUSTAVO GOMES LINCEVICIUS', 'operator', true, false, '{}', NOW(), NOW()),
  ('stcisterna', 'stcisterna@gruporoveri.com', 'STEFANIE CAROLINE OLIVEIRA CISTERNAS', 'operator', true, false, '{}', NOW(), NOW()),
  ('emsiqueira', 'emsiqueira@gruporoveri.com', 'EMILLY KAMILLY SIQUEIRA DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('jenvieira', 'jenvieira@gruporoveri.com', 'JENNIFER LIZ DE ALMEIDA VIEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('rasolera', 'rasolera@gruporoveri.com', 'RAUL SABINO SOLERA', 'operator', true, false, '{}', NOW(), NOW()),
  ('brestrela', 'brestrela@gruporoveri.com', 'BRENDA MORGAN ESTRELA DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('jaaraujo', 'jaaraujo@gruporoveri.com', 'JADE ALVES DE ARAUJO', 'operator', true, false, '{}', NOW(), NOW()),
  ('daneto', 'daneto@gruporoveri.com', 'DANIELA MOURA ANDRADE', 'operator', true, false, '{}', NOW(), NOW()),
  ('hagomes', 'hagomes@gruporoveri.com', 'HAYANE DE MOURA GOMES', 'operator', true, false, '{}', NOW(), NOW()),
  ('lachinconi', 'lachinconi@gruporoveri.com', 'LORENA FACHINCONI DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('prleite', 'prleite@gruporoveri.com', 'PRISCILA NUNES LEITE', 'operator', true, false, '{}', NOW(), NOW()),
  ('prprates', 'prprates@gruporoveri.com', 'PRISCILA PRATES', 'operator', true, false, '{}', NOW(), NOW()),
  ('glsa', 'glsa@gruporoveri.com', 'GLEICE QUELLI CONCEICAO DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('hemacedo', 'hemacedo@gruporoveri.com', 'HEITOR JUNIOR FERREIRA MACEDO', 'operator', true, false, '{}', NOW(), NOW()),
  ('lavidrade', 'lavidrade@gruporoveri.com', 'LAYSLA VITORIA CARDOSO DE ANDRADE', 'operator', true, false, '{}', NOW(), NOW()),
  ('igmedeiros', 'igmedeiros@gruporoveri.com', 'IGOR SILVA DE MEDEIROS', 'operator', true, false, '{}', NOW(), NOW()),
  ('kaarves', 'kaarves@gruporoveri.com', 'KAUAN ARAUJO ALVES', 'operator', true, false, '{}', NOW(), NOW()),
  ('macertier', 'macertier@gruporoveri.com', 'MARCELLE CERTIER', 'operator', true, false, '{}', NOW(), NOW()),
  ('sosotorolli', 'sosotorolli@gruporoveri.com', 'SOFIA ALMEIDA SOTOROLLI', 'operator', true, false, '{}', NOW(), NOW()),
  ('jualmeida', 'jualmeida@gruporoveri.com', 'JULIA DOS SANTOS ALMEIDA', 'operator', true, false, '{}', NOW(), NOW()),
  ('jusilveira', 'jusilveira@gruporoveri.com', 'JULIA GARZO SILVEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('ledoleite', 'ledoleite@gruporoveri.com', 'LETICIA DOS SANTOS SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('namachado', 'namachado@gruporoveri.com', 'NATHALI OLIVEIRA MACHADO', 'operator', true, false, '{}', NOW(), NOW()),
  ('mavasantos', 'mavasantos@gruporoveri.com', 'MANUELE SILVA SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('cagodsantos', 'cagodsantos@gruporoveri.com', 'CAROLINI GOMES DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('gadeolitos', 'gadeolitos@gruporoveri.com', 'GABRIEL DE OLIVEIRA SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('sasantos', 'sasantos@gruporoveri.com', 'SARAH ALMEIDA DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('dabarbosa', 'dabarbosa@gruporoveri.com', 'DAYERE DIAS BARBOSA', 'operator', true, false, '{}', NOW(), NOW()),
  ('ermedrado', 'ermedrado@gruporoveri.com', 'ERICA DA SILVA MEDRADO', 'operator', true, false, '{}', NOW(), NOW()),
  ('ismaceza', 'ismaceza@gruporoveri.com', 'ISABELLY CRISTINA MACEDO DE SOUSA', 'operator', true, false, '{}', NOW(), NOW()),
  ('jepergentino', 'jepergentino@gruporoveri.com', 'JENNIFER GABRIELLE PERGENTINO', 'operator', true, false, '{}', NOW(), NOW()),
  ('jumarin', 'jumarin@gruporoveri.com', 'JULIA BRUNO DIAS MARIN', 'operator', true, false, '{}', NOW(), NOW()),
  ('lualtos', 'lualtos@gruporoveri.com', 'LUDMILLA ALVES DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('mamouli', 'mamouli@gruporoveri.com', 'MATHEUS MOURA DE LIMA', 'operator', true, false, '{}', NOW(), NOW()),
  ('masabio', 'masabio@gruporoveri.com', 'MATHEUS SABIO', 'operator', true, false, '{}', NOW(), NOW()),
  ('nadastos', 'nadastos@gruporoveri.com', 'NATALIA DA SILVA SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('nivestini', 'nivestini@gruporoveri.com', 'NICOLLY ALVES SANTINI DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('nypeixoto', 'nypeixoto@gruporoveri.com', 'NYCOLLAS REYDAN ALVES PEIXOTO', 'operator', true, false, '{}', NOW(), NOW()),
  ('viveiradao', 'viveiradao@gruporoveri.com', 'VINICIUS OLIVEIRA BRANDAO DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('anlohi', 'anlohi@gruporoveri.com', 'ANDREIA LOHANI SOUZA DE ARAUJO', 'operator', true, false, '{}', NOW(), NOW()),
  ('amaporto', 'amaporto@gruporoveri.com', 'AMANDA SANTOS PORTO', 'operator', true, false, '{}', NOW(), NOW()),
  ('vsouza', 'vsouza@gruporoveri.com', 'VERONICA APARECIDA DE SOUZA', 'operator', true, false, '{}', NOW(), NOW()),
  ('gufsilva', 'gufsilva@gruporoveri.com', 'GUSTAVO FERREIRA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('magaldino', 'magaldino@gruporoveri.com', 'MARIANE VITORIA GALDINO', 'operator', true, false, '{}', NOW(), NOW()),
  ('nirabisquim', 'nirabisquim@gruporoveri.com', 'NILVA MARIA RABISQUIM', 'operator', true, false, '{}', NOW(), NOW()),
  ('emlima', 'emlima@gruporoveri.com', 'EMILLY GONCALVES DE LIMA', 'operator', true, false, '{}', NOW(), NOW()),
  ('jocruz', 'jocruz@gruporoveri.com', 'JOYCE CRUZ DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('leaferreira', 'leaferreira@gruporoveri.com', 'LEANNE SLENY FERREIRA FREITAS', 'operator', true, false, '{}', NOW(), NOW()),
  ('lubispo', 'lubispo@gruporoveri.com', 'LUIZA ROSA BISPO SOUSA', 'operator', true, false, '{}', NOW(), NOW()),
  ('gaannunciato', 'gaannunciato@gruporoveri.com', 'GABRIELLA SILVESTRE ANNUNCIATO', 'operator', true, false, '{}', NOW(), NOW()),
  ('giannunciato', 'giannunciato@gruporoveri.com', 'GIOVANNA SILVESTRE ANNUNCIATO', 'operator', true, false, '{}', NOW(), NOW()),
  ('eldias', 'eldias@gruporoveri.com', 'ELIANE JOSEFA DIAS', 'operator', true, false, '{}', NOW(), NOW()),
  ('rosalves', 'rosalves@gruporoveri.com', 'ROSANE CORREA SANTOS ALVES', 'operator', true, false, '{}', NOW(), NOW()),
  ('yulima', 'yulima@gruporoveri.com', 'YURI CRISPIM DE LIMA', 'operator', true, false, '{}', NOW(), NOW()),
  ('gelinhares', 'gelinhares@gruporoveri.com', 'GERUSIA MARTA FERNADES LINHARES', 'operator', true, false, '{}', NOW(), NOW()),
  ('kapereira', 'kapereira@gruporoveri.com', 'KAUE RAMOS PEREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('kanslima', 'kanslima@gruporoveri.com', 'KAUANY SILVA LIMA', 'operator', true, false, '{}', NOW(), NOW()),
  ('maximenes', 'maximenes@gruporoveri.com', 'MATHEUS DE MARTIN XIMENES', 'operator', true, false, '{}', NOW(), NOW()),
  ('hefrsantos', 'hefrsantos@gruporoveri.com', 'HELOISA FREITAS DOS SANTOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('valicosta', 'valicosta@gruporoveri.com', 'VANESSA LIMA DA COSTA', 'operator', true, false, '{}', NOW(), NOW()),
  ('taresilva', 'taresilva@gruporoveri.com', 'TAYNARA REJANE DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('rafilonzi', 'rafilonzi@gruporoveri.com', 'RAFAEL ALONSO RODRIGUES FILONZI', 'operator', true, false, '{}', NOW(), NOW()),
  ('viguimaraes', 'viguimaraes@gruporoveri.com', 'VICTORIA LORRANY AMORIM GUIMARAES', 'operator', true, false, '{}', NOW(), NOW()),
  ('madanes', 'madanes@gruporoveri.com', 'MARIA DA CONCEICAO NUNES', 'operator', true, false, '{}', NOW(), NOW()),
  ('vibueno', 'vibueno@gruporoveri.com', 'VINICIUS COSTA BUENO', 'operator', true, false, '{}', NOW(), NOW()),
  ('PSFREITAS', 'PSFREITAS@gruporoveri.com', 'PIETRA SILVA FREITAS', 'operator', true, false, '{}', NOW(), NOW()),
  ('RENJESUS', 'RENJESUS@gruporoveri.com', 'RENATO CALIXTO DE JESUS', 'operator', true, false, '{}', NOW(), NOW()),
  ('ANFIORENTINI', 'ANFIORENTINI@gruporoveri.com', 'ANA CLARA FIORENTINI', 'operator', true, false, '{}', NOW(), NOW()),
  ('LARIRODRIGUES', 'LARIRODRIGUES@gruporoveri.com', 'LARISSA RODRIGUES DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('INBACCON', 'INBACCON@gruporoveri.com', 'DIEGO BACCON', 'operator', true, false, '{}', NOW(), NOW()),
  ('VALEMOS', 'VALEMOS@gruporoveri.com', 'VALDINETE RODRIGUES DE LEMOS', 'operator', true, false, '{}', NOW(), NOW()),
  ('FEJNAKAMURA', 'FEJNAKAMURA@gruporoveri.com', 'FELIPE JUN COMESSU NAKAMURA', 'operator', true, false, '{}', NOW(), NOW()),
  ('GPAPINO', 'GPAPINO@gruporoveri.com', 'GABRIELLY PAPINI ARAUJO', 'operator', true, false, '{}', NOW(), NOW()),
  ('BRRIBEIRO', 'BRRIBEIRO@gruporoveri.com', 'BRENDA RODRIGUES RIBEIRO', 'operator', true, false, '{}', NOW(), NOW()),
  ('LPOLIVEIRA', 'LPOLIVEIRA@gruporoveri.com', 'LETICIA PAIS DE OLIVEIRA      ', 'operator', true, false, '{}', NOW(), NOW()),
  ('CCORREIA', 'CCORREIA@gruporoveri.com', 'CELMA DAIANE DO NASCIMENTO', 'operator', true, false, '{}', NOW(), NOW()),
  ('BTESILVA', 'BTESILVA@gruporoveri.com', 'BEATRIZ TEIXEIRA DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('CAMALMEIDA', 'CAMALMEIDA@gruporoveri.com', 'CAMILA DE ALMEIDA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('TAYLSANTOS', 'TAYLSANTOS@gruporoveri.com', 'TAYNA DOS SANTOS LIMA FERREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('DOOLIVEIRA', 'DOOLIVEIRA@gruporoveri.com', 'DOUGLAS VALENTIM', 'operator', true, false, '{}', NOW(), NOW()),
  ('RAFAMELO', 'RAFAMELO@gruporoveri.com', 'RAFAELA MELO DA SILVA', 'operator', true, false, '{}', NOW(), NOW()),
  ('SOPHIA', 'SOPHIA@gruporoveri.com', 'SOPHIA DE JESUS FERREIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('VLFILHO', 'VLFILHO@gruporoveri.com', 'VLADINEI BUGUAS FILHO', 'operator', true, false, '{}', NOW(), NOW()),
  ('TSIOLIVEIRA', 'TSIOLIVEIRA@gruporoveri.com', 'THAIS SILVA OLIVEIRA', 'operator', true, false, '{}', NOW(), NOW()),
  ('TAMRODRIGUES', 'TAMRODRIGUES@gruporoveri.com', 'TATIANA DE MARQUES RODRIGUES', 'operator', true, false, '{}', NOW(), NOW()),
  ('mapere', 'mapere@gruporoveri.com', 'MARIA IZABELLE DE FREITAS PERE', 'operator', true, false, '{}', NOW(), NOW())

ON CONFLICT (email) DO UPDATE SET
  username = EXCLUDED.username,
  name = EXCLUDED.name,
  role = EXCLUDED.role,
  is_active = EXCLUDED.is_active,
  updated_at = NOW();

SELECT COUNT(*) as total_operadores FROM users WHERE role = 'operator';
